### ISSUE TITLE
Fatal error: Call to a member function Execute() on a non-object in /var/www/html/icasus/icasus/public/index.php on line 55

### ISSUE THREAD

**Issue by skeksi** [Universidad-de-Sevilla/icasus#1]
Hola,

Siguiendo las instrucciones de instalación, usando el código que teneis en github, estoy intentando montar la aplicación y me encuentro con el siguiente error al intentar acceder (http://localhost/icasus/public/index.php):

Fatal error: Call to a member function Execute() on a non-object in /var/www/html/icasus/icasus/public/index.php on line 55

(que se corresponde con la línea de código: $adodb->Execute("SET NAMES UTF8");)

PHP: he probado con varias versiones (7.2, 7.1, 7.0, 5.7, 5.6, 5.5, y 5.4) y con todas idem.

¿Sabeis que puede ser? 

(he probado tanto con apache como con nginx y lo mismo. También he probado con mysql 7, 6 y 5)

Saludos

**Comment by juananruiz** [comment]
Hola,

Parece un error de conexión a la base de datos, pero es raro que no te lo muestre en la línea donde se realiza la conexión. ¿Has configurado que se muestren todos lo errores?

He hecho pruebas con todas las versiones de PHP que comentas, con mySQL 5.5, 5.6 y 5.7 y Apache2. 

Estoy a tu disposición en lo que pueda ayudarte.

Saludos cordiales,
					&8.)-juanan

Juan Antonio Ruiz Rivas
Planificación de Recursos Humanos
Universidad de Sevilla
9544 87458 - 658291111 - juanan@us.es
Hoy puede ser un gran día

**Comment by skeksi** [comment]
Cierto,  acabo de ver que me faltaba el driver de mysql para php O.o

Ya tira.

Gracias

**Comment by juananruiz** [comment]
Me alegro!!! Cualquier sugerencia (o ayuda) es bienvenida
